### ISSUE TITLE
binary packages?

### ISSUE THREAD

**Issue by teras** [flokli/borg2restic#1]
Hello.
Any plans on distributing binary bundles/packages, since from what I understand, at least restic (and yours of course) can't be taken off shelf. Adding borg also would be a nice touch :)

**Comment by flokli** [comment]
Hmh, I originally didn't plan to - I'd prefer https://github.com/restic/restic/pull/3200 or something similar to get merged, and considering this code here is a very small go project that can be easily built, I didn't plan to add releases and attach binaries to it.

If the restic PR will still takes a while, I circle back on this, potentially provide a container image with all 3 binaries inside (and restic patched), but there's some UX problems with running it in a container, such as running as a different user / different hostname, and having to juggle with even more mountpoints.

**Comment by teras** [comment]
I am using restic beta version for some time now, since I need compression and there's no direct will to make a new release. At any case, I'd say you should consider, for easability reasons, to provide a combined package, as a docker or even better as an appimage. If you want I can help you with this.

**Comment by Edzilla2000** [comment]
The pull request is still not available in restic and I'm very interested in being able to use --set-path
Would providing binaries be possible? 
Thanks!

**Comment by flokli** [comment]
@Edzilla2000 yeah, the upstream PR got closed and things didn't move further.

However, I don't intend to keep maintaining that patch, and keeping it updated with future restic development.

It looks like https://github.com/rogivorakam/restic/commit/3c379740abb0334bb40eb6b740f721fde766ed47 contains a resurrection/refresh of that patch - it's probably best if you try to build restic from there.
